title: white5moke
email: chris.is.rad@pm.me
description: >- # this means to ignore newlines until "baseurl:"
  defender of information. value is soul! ^.^
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://white5moke.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  white5moke

locale: "en-US"

# Build settings
#theme: minima
remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"

plugins:
  - jekyll-feed
  - jekyll-sitemap
