title: white5moke
email: chris.is.rad@pm.me
description: >- # this means to ignore newlines until "baseurl:"
  defender of information. value is soul! ^.^
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://white5moke.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  white5moke

# Build settings
#theme: minima
theme: jekyll-theme-basically-basic
plugins:
  - jekyll-feed
